baseurl = "http://ajatusrikos.fi"
languageCode = "fi"
title = "Kyhäelmä ajatuksistani ja kokemuksistani"
author = "Topi Tuulensuu"


[params]
  logo      = "/nassu.jpeg"
  copyright = "Topi Tuulensuu. Saa jakaa ja kopioida."
  twitter   = "https://twitter.com/topituulensuu"
  github    = "https://github.com/totu/"
  email     = "topi.tuulensuu@gmail.com"

canonifyurls = true
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
