# To learn about configuring soupalt, visit https://baturin.org/projects/soupault
[settings]
  strict = true
  verbose = false
  build_dir = "build"
  site_dir = "site"
  default_template = "templates/main.html"
  content_selector = "body"
  doctype = "<!DOCTYPE html>"
  clean_urls = true